networks:
  my_network:
  
services:
  service1:
    image: demo001:latest
    networks:
      - my_network
    ports:
      - 8882:8880
    environment:
      - "SPRING_PROFILES_ACTIVE=dev"

  service2:
    image: demo001:latest
    networks:
      - my_network
    ports:
      - 8883:8880
    environment:
      - "SPRING_PROFILES_ACTIVE=dev"

  nginx_load_balancer:
    image: nginx_load_balancer:latest
    networks:
      - my_network
    ports:
      - 8888:80
    depends_on:
      - service1
      - service2