name: instagram_auth_dart_service
description: A server app using the shelf package and Docker.
version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.18.5 <3.0.0'

dependencies:
  args: ^2.0.0
  collection: ^1.17.0
  dart_jsonwebtoken: ^2.6.2
  dbcrypt: ^2.0.0
  get_it: ^7.2.0
  shelf: ^1.1.0
  shelf_router: ^1.0.0
  uuid: ^3.0.7

dev_dependencies:
  http: ^0.13.0
  lints: ^2.0.0
  test: ^1.15.0
